{
  exclude = {
    uncommon = ''
      MACINTOSH_DRIVERS n
      INFINIBAND n
      HAMRADIO n
      CAN n
      FIREWIRE n
      MEDIA_ANALOG_TV_SUPPORT n
      MEDIA_DIGITAL_TV_SUPPORT n
      MEDIA_RADIO_SUPPORT n
      MEDIA_PCI_SUPPORT n
      MEDIA_TUNER n
      IRDA n
      LUSTRE_FS n
      INPUT_TABLET n
      CHROME_PLATFORMS n
    '';
    fs = ''
      ACORN_PARTITION n
      AIX_PARTITION n
      OSF_PARTITION n
      AMIGA_PARTITION n
      ATARI_PARTITION n 
      MAC_PARTITION n
      SUN_PARTITION n
      KARMA_PARTITION n
      MINIX_SUBPARTITION n
      SOLARIS_X86_PARTITION n
      ULTRIX_PARTITION n
      EXT2_FS n
      REISERFS_FS n
      JFS_FS n
      XFS_FS n
      GFS2_FS n
      NILFS2_FS n
      F2FS_FS n
    '';
    wlan= ''
      WLAN_VENDOR_CISCO n
      WLAN_VENDOR_ATMEL n
      WLAN_VENDOR_ADMTEK n
      WLAN_VENDOR_ATH n
      WLAN_VENDOR_ATMEL n
      WLAN_VENDOR_BROADCOM n
      WLAN_VENDOR_INTERSIL n
      WLAN_VENDOR_MARVELL n
      WLAN_VENDOR_MEDIATEK n
      WLAN_VENDOR_RALINK n
      WLAN_VENDOR_REALTEK n
      WLAN_VENDOR_RSI n
      WLAN_VENDOR_ST n
      WLAN_VENDOR_TI n
      WLAN_VENDOR_ZYDAS n
      WLAN_VENDOR_QUANTENNA n
    '';
    net = ''
      NET_VENDOR_3COM n
      NET_VENDOR_ADAPTEC n
      NET_VENDOR_AGERE n 
      NET_VENDOR_ALACRITECH n
      NET_VENDOR_ALTEON n
      NET_VENDOR_AMAZON n
      NET_VENDOR_AMD n
      NET_VENDOR_AQUANTIA n
      NET_VENDOR_ARC n
      NET_VENDOR_ATHEROS n
      NET_VENDOR_AURORA n
      NET_VENDOR_BROADCOM n
      NET_VENDOR_BROCADE n
      NET_VENDOR_CAVIUM n
      NET_VENDOR_CHELSIO n
      NET_VENDOR_CISCO n
      NET_VENDOR_CORTINA n
      NET_VENDOR_DEC n
      NET_VENDOR_DLINK n
      NET_VENDOR_EMULEX n
      NET_VENDOR_EZCHIP n
      NET_VENDOR_EXAR n
      NET_VENDOR_HP n
      NET_VENDOR_HUAWEI n
      NET_VENDOR_INTEL n
      NET_VENDOR_MARVELL n
      NET_VENDOR_MELLANOX n
      NET_VENDOR_MICREL n
      NET_VENDOR_MICROCHIP n
      NET_VENDOR_MYRI n
      NET_VENDOR_NATSEMI n
      NET_VENDOR_NETRONOME n
      NET_VENDOR_NI n
      NET_VENDOR_NVIDIA n
      NET_VENDOR_OKI n
      NET_VENDOR_QLOGIC n
      NET_VENDOR_QUALCOMM n
      NET_VENDOR_RENESAS n
      NET_VENDOR_RDC n
      NET_VENDOR_ROCKER n
      NET_VENDOR_SAMSUNG n
      NET_VENDOR_SEEQ n
      NET_VENDOR_SILAN n
      NET_VENDOR_SIS n
      NET_VENDOR_SOLARFLARE n
      NET_VENDOR_SMSC n
      NET_VENDOR_SOCIONEXT n
      NET_VENDOR_STMICRO n
      NET_VENDOR_SUN n
      NET_VENDOR_TEHUTI n
      NET_VENDOR_TI n
      NET_VENDOR_VIA n
      NET_VENDOR_WIZNET n
      NET_VENDOR_SYNOPSYS n
    '';
  };
}
